/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "李十一啊",
  "description": "李十一啊的前端笔记记录",
  "base": "/docs/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "李十一啊"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "javascrpt笔记，前端面试，vue，vue3、前端自动化构建工具详解、react知识分享、css知识分享等前端知识分享"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "李十一啊",
        "tagline": "前端笔记",
        "actionText": "快速上手 →",
        "actionLink": "/docs/js/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-649ce064",
      "path": "/"
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-743c9315",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "关于我",
        "link": "/about/",
        "target": "_blank"
      },
      {
        "text": "js",
        "link": "https://baidu.com",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "vue",
        "ariaLabel": "vue Menu",
        "items": [
          {
            "text": "vue2",
            "link": "/vue/vue2/"
          },
          {
            "text": "vue3",
            "link": "/vue/vue3/"
          }
        ]
      },
      {
        "text": "interview",
        "ariaLabel": "interview Menu",
        "items": [
          {
            "text": "js",
            "link": "/interview/js/"
          },
          {
            "text": "css",
            "link": "/interview/css/"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "Group 1",
        "path": "/foo/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/"
        ]
      },
      {
        "title": "Group 2",
        "children": [],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}